name: apriori
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - spacy
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - tqdm
  - pip:
      - tokenizers
